### PR TITLE
Add mobile menu

### LINKED ISSUE #31: Responsive (mobile) menu takes too much space
On a smart phone (width 767px and lower) the menu is vertical and takes quite a lot of space, so no content below is visible without "scrolling". Thus when you click on a link in the menu, the visitor will see almost no response - the appropriate page is loaded, but still sees only the menu.

The current page could be somehow highlighted in the menu, or (better) hamburger menu should be for the mobile responsive version.

Maybe some menu re-composition could include also https://github.com/mozilla/One-Mozilla-blog/issues/8.

### PR DESCRIPTION
**Pull request by MikkCZ**
Fix #31. Inspired by mozilla.si.

@craigcook r?

### CODE REVIEW

**Comment by MikkCZ** [comment]
You can already see it in action on https://www.mozilla.cz/

**Comment by MikkCZ** [comment]
I have noticed this working only when logged in, probably because jQuery is loaded from administration first. I have fixed this now.

**Comment by MikkCZ** [comment]
@craigcook Thank you for merging #54. Please let me know, if this PR is also OK. I have noticed that the resposive menu is already implemented on some mozilla.org pages in with a completely different style, but the my way seemed much simpler and more consistent with the rest of the blog theme to me.

**Comment by craigcook** [comment]
For a mobile-friendly treatment of the main menu, I don't think managing a completely separate menu is the best approach. Although this does at least solve the immediate problem of the main menu filling up small screens, what we really need to do is change the style/behavior of that existing menu so it converts automatically into a hidden "hamburger" menu in small viewports. I'm working on a brand update for One Mozilla that will address this (sorry it's taking so long). 

So I don't think we should merge this pull request as it is because I don't want to add an extra menu, but I also don't think it's worth your time doing any additional work to change it when I've already got another solution nearly complete. Sorry! 😞

I hope to have the brand refresh finished very soon, I just keep getting sidetracked by other priorities so I've only been able to work on it in short bursts.

**Comment by MikkCZ** [comment]
Np, I have created it as a separate menu, because I could not decide, what should be displayed in the hamburger menu in case both top and main menu are used. Thus I have added this as an option in case you want to make the mobile menu completely custom.

I will keep this in my branch, just in case.

**Pull request closed without merging**
