### PR TITLE
Fix Bug 1279110 - Create a WordPress theme for Firefox Nightly

### PR DESCRIPTION
**Pull request by kyoshino**
@craigcook r?

Demo server: https://carlton.britegrid.com/

### CODE REVIEW

**Comment by MikkCZ** [comment]
Looking at the demo site, I am not sure about the contrast between the text and background, especially the light part (ocean) of the planet, and the sidebar and the lights on the continent.

**Comment by kyoshino** [comment]
Thanks @MikkCZ, maybe the fixed background doesn't work well. I've changed it to scroll.

**Comment by MikkCZ** [comment]
The sidebar is still worse readable on the top of the light dots on the continent, but for the text of the post it's much better now.

**Comment by pascalchevrel** [comment]
would it be possible to have a nightly icon or wormark instead of the generic mozilla logo for og:image?

**Comment by kyoshino** [comment]
Added the Nightly favicon and og:image. I think the contrast is okay.

**Comment by pascalchevrel** [comment]
The title of the blog is just Firefox Nightly, what do you think about using the wordmark for that instead of text ? https://raw.githubusercontent.com/pascalchevrel/nightly-assets/master/styleguide/firefox-nightly_wordmark-only_RGB.png

**Comment by kyoshino** [comment]
Is there any chance of changing the title to Firefox Nightly Blog or whatever?

**Comment by pascalchevrel** [comment]
good idea and changed with an added tagline:

Firefox Nightly News
Let's improve quality, build after build!

You can ignore my wordmark suggestion :)

**Comment by kyoshino** [comment]
Updated my [demo site](https://carlton.britegrid.com/) accordingly 😺

**Comment by craigcook** [comment]
Code looks good, r+ 🌃  
If @pascalchevrel is happy with the design I can merge this and install it in production. Any reason to wait? We can always keep tweaking later.

**Comment by pascalchevrel** [comment]
No reason to wait as it is an improvement to what we have :)

**Comment by kyoshino** [comment]
How can we deploy the new theme?

**Comment by craigcook** [comment]
Sorry for the delay. I added styles for comments in 3c00315cb8c4ca552256fa9cf90c0e457af2e653 and I've just deployed the theme to production and activated it on the blog: https://blog.nightly.mozilla.org/

**Pull request merged**
