### PR TITLE
Fix comment style on Nightly blog

### PR DESCRIPTION
**Pull request by kyoshino**
This improves the [comment widget’s style on the Nightly blog](https://blog.nightly.mozilla.org/2016/10/17/better-default-bookmarks-for-nightly/#social).

Cc @pascalchevrel

### CODE REVIEW

**Comment by kyoshino** [comment]
Screenshot:
screen shot 2016-10-20 at 19 35 28

**Comment by pascalchevrel** [comment]
@craigcook could you have a look at it please? Thanks

**Comment by craigcook** [comment]
I've just pushed this update to production.

**Comment by kyoshino** [comment]
Thanks!

**Comment by pascalchevrel** [comment]
Looks good, thanks guys :)

**Pull request merged**
